// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iczaitarntubjtiokeic.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImljemFpdGFybnR1Ymp0aW9rZWljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMzQxMzQsImV4cCI6MjA2OTcxMDEzNH0.WbgMd9yGMu7yUb8j4Y6gg---BunTIXtNWFVdO_LjcVs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});